# Header
menu:
  Litesuits: '#'
  Docs: /
  About: /
donate: '#donations'

contacts:
  About Design: '#'
  Github: 'https://github.com/litesuits'
  Blog: '#'
  EOE: '#'
  zhihu: '#'

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: